#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd &
lxpolkit &
nm-applet &
$HOME/.config/polybar/launch.sh
nitrogen --restore &
picom --experimental-backends &

#------------ Monitor configuration ---------------------------#

#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor eDP-1 -d        ﭮ 
bspc monitor eDP-1 -d 1 2 3 4 5 6 
#------------ Frame configuration -----------------------------#

bspc config border_width         2
bspc config window_gap          25
bspc config top_padding		35
bspc config bottom_padding	0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

#------------ Color scheme configuration ----------------------#

bspc config normal_border_color		"#121212"
bspc config active_border_color		"#121212"
bspc config focused_border_color	"#D6645D"
bspc config presel_feedback_color	"#D6645D"

#------------ BSPWM Rules -------------------------------------#

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Code desktop='^2'
bspc rule -a firefox desktop='^3'
bspc rule -a Brave-browser-dev desktop='^3'
bspc rule -a "Tor Browser" desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a discord desktop="^4"
bspc rule -a Brave-browser-nightly desktop="^3"
bspc rule -a "Spotify" desktop="^5"
